= Informe del Trabajo Práctico Programación II

Integrantes
Agustina Mendez, <agustina.996@hotmail.com> 
Kevin Montenegro, <kevinmontenegroac@gmail.com> 

:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción
La empresa de transportes “Expreso Libre” posee una flota de transportes para trasladar los productos que vende desde sus depósitos hacia sus centros de distribución ubicados en distintos puntos del país. La Empresa cuenta con distintos tipos de transportes, Camión Trailer, Camión MegaTrailer y Flete, y necesita automatizar las operaciones y consultas habituales que responden a las actividades de carga y entrega de la mercadería. Los productos que se transportan pueden necesitar refrigeración o no, por lo cual la empresa cuenta con un depósito para productos con necesidad de refrigeración y otro depósito sin ese requerimiento.

== Implementación 

Para la implementación se consideraron las siguientes clases

=== Empresa
En primer lugar se inicializan las variables y se crean y agregan los depositos (uno con refrigeracion y otro sin) a la lista de depositos
Se agregan los destinos nuevos a la lista de destinos
  
[source, java]
----
  private int cuit;
  private String nombre;
  private List<Deposito> depositos; //contiene los dos depositos de la empresa
  private List<Transporte> transportes; //no tiene repetidos
  private List<Destino> destinos; //no tiene repetidos
  private HashMap<String, String> destinosAsignados; //no tiene repetidos
  
  public Empresa(String cuit, String nombre, int capacidadDeposito);
  
  void agregarDestino(String destino, int km){
    for (Destino d : destinos) {
      if (d.getDestino().equals(destino)) {
        throw new RuntimeException("El destino ya existe");
      }
    }
    Destino destino_ = new Destino(destino, km);
    this.destinos.add(destino_);
  }
----

Los metodos para agregar transportes verifican que la matricula no este en la lista con el método auxiliar existe Matricula (matricula)

[source, java]
----
void agregarTrailer(String matricula, double cargaMax, double capacidad, boolean tieneRefrigeracion, double costoKm, double segCarga){
  if (!existeMatricula(matricula)) {
    Trailer transporte = new Trailer(matricula, cargaMax, capacidad, tieneRefrigeracion, costoKm, segCarga);
    transportes.add(transporte);
  }
}

void agregarMegaTrailer(String matricula, double cargaMax, double capacidad, boolean tieneRefrigeracion, double costoKm, double segCarga, double costoFijo, double costoComida){
  if (!existeMatricula(matricula)) {
    MegaTrailer transporte = new MegaTrailer(matricula, cargaMax, capacidad, tieneRefrigeracion, costoKm, segCarga, costoFijo, costoComida);
    transportes.add(transporte);
  }
}

void agregarFlete(String matricula, double cargaMax, double capacidad, double costoKm, int cantAcompaniantes, double costoPorAcompaniante){
  if (!existeMatricula(matricula)) {
    Flete transporte = new Flete(matricula, cargaMax, capacidad, costoKm, cantAcompaniantes, costoPorAcompaniante);
    transportes.add(transporte);
  }
}
----

Para asignarle un destino a un transporte, primero verificamos que el destino y la matricula esten cargadas en el sistema. Luego, con el metodo auxiliar buscarTransporte (matricula) obtenemos todos los datos del transporte.
Para asignar el destino tambien debemos verificar que:
* El transporte no se encuentre en viaje
* En el caso de ser un Trailer, que el destino se encuentre a menos de 500km
* En el caso de ser un Mega Trailer, que el destino se encuentre a mas de 500km

[source, java]
----
  public void asignarDestino(String matricula, String destino){
    if (existeDestino(destino) && existeMatricula(matricula)) {
      Transporte transporte = buscarTransporte(matricula);
      if (!transporte.isEstaEnViaje()) {
        if (transporte instanceof Trailer && cantKilometros(destino) > 500) {
          throw new RuntimeException("El destino se encuentra a mas de 500km");
        } else if (transporte instanceof MegaTrailer && cantKilometros(destino) < 500) {
          throw new RuntimeException("El destino se encuentra a menos de 500km");
        } else {
          destinosAsignados.put(matricula, destino);
          transporte.setDestino(destino);
        }
      }
    } else {
      throw new RuntimeException("No existe la matricula o el destino que se quiere asignar");
    }
  }
----
Recorre la lista de depositos y verifica que deposito y paquete tengan (o no) refrigeracion para incorporar los paquetes al deposito adecuado

[source, java]
----
  public boolean incorporarPaquete(String destino, double peso, double volumen, boolean necesitaRefrigeracion) {
    Paquete paquete = new Paquete(destino, peso, volumen, necesitaRefrigeracion);
    for (Deposito d : depositos) {
      if ((necesitaRefrigeracion && d.tieneRefrigeracion()) || (!necesitaRefrigeracion && !d.tieneRefrigeracion())) {
        if (d.tieneCapacidad() && paquete.getVolumen() <= d.getCapacidad()) {
          d.agregarPaquete(paquete);
          return true;
        }
      }
    }
    return false;
  }
----
Verificamos que exista la matricula, que tenga asignado un destino y que no este en viaje
Recorremos con un for de depositos para seleccionar según si el transport e tiene refrigeracion o no, el deposito adecuado
En principio, intentamos hacer la carga de paquetes con otro for pero al intentar eliminar el paquete del deposito no funcionaba
Como solución usamos un iterador para ir agregando al transporte y eliminando del deposito los paquetes
Ademas, usamos un metodo auxiliar aumentarCapacidad () en deposito

[source, java]
----
  public double cargarTransporte(String matricula) {
    if (existeMatricula(matricula) && tieneAsignadoDestino(matricula)) {
    Transporte transporte = buscarTransporte(matricula);
      if (!transporte.isEstaEnViaje()) {
        for (Deposito d : depositos) {
          if ((d.tieneRefrigeracion() && transporte.tieneRefrigeracion()) ||!d.tieneRefrigeracion() && !transporte.tieneRefrigeracion()) {
            Iterator<Paquete> iterador = d.getPaquetes().iterator();
            while (!d.getPaquetes().isEmpty() && iterador.hasNext()) {
              Paquete p = iterador.next();
              transporte.cargarPaquete(p);
              iterador.remove();
              d.aumentarCapacidad();
            }
            return transporte.getCargaActual();
          }
        }
      }
    }
    throw new RuntimeException("No se puede cargar el transporte");
  }

  public void iniciarViaje(String matricula) {
    Transporte transporte = buscarTransporte(matricula);
    if (transporte.isEstaEnViaje() || !tieneAsignadoDestino(matricula) || transporte.getPaquetes().size() < 1) {
      throw new RuntimeException("No tiene mercaderia cargada o ya esta en viaje");
    } else {
      transporte.setEstaEnViaje(true);
    }
  }
  
  public void finalizarViaje(String matricula) {
    Transporte transporte = buscarTransporte(matricula);
    if (!transporte.isEstaEnViaje()) {
      throw new RuntimeException("No esta en viaje");
    } else {
      transporte.eliminarPaquete();
      destinosAsignados.remove(matricula);
      transporte.setEstaEnViaje(false);
      transporte.setDestino("");
    }
  }
----
Si el transporte esta en viaje, obtiene el costo con ayuda de la funcion auxiliar y obtener KmDestino (matricula) y con costoViaje ()

[source, java]
----
  public double obtenerCostoViaje(String matricula) {
    Transporte transporte = buscarTransporte(matricula);
    if (!transporte.isEstaEnViaje()) {
      throw new RuntimeException("No esta en viaje");
    } else {
        return transporte.getCostoKm() * obtenerKmDestino(matricula) + transporte.costoViaje();
    }
  }
----
Recorriendo la lista de transportes verificamos no compara r la misma matricula y luego verificamos con equals que los transportes sean iguales
Se considera igual si:
* Son el mismo tipo de transporte
* Tiene n el mismo destino
* Llevan la misma carga de paquetes

[source, java]
----
  public String obtenerTransporteIgual(String matricula) {
    Transporte transporte = buscarTransporte(matricula);
    for (Transporte t : transportes) {
      if (t.getMatricula() != matricula && t.equals(transporte)) {
        return t.getMatricula();
      }
    }
    return null;
  }
----

=== Deposito
Agregar paquete: agrega el paquete a la lista y resta en 1 la capacidad del deposito. Una vez que eliminamos el paquete de la lista, aumentamos en 1 la capacidad del deposito

[source, java]
----
  private HashSet<Paquete> paquetes;
  private boolean refrigeracion;
  private Integer capacidad;
  public Deposito (boolean refrigeracion, int capacidad)

  public void agregarPaquete(Paquete paquete) {
    paquetes.add(paquete);
    capacidad = capacidad - 1;
  }

  public void aumentarCapacidad() {
    capacidad = capacidad + 1;
  }
  
  public boolean tieneCapacidad() {
    return paquetes.size() < capacidad;
----

=== Transporte
Que contiene los metodos para verificar si queda lugar en el transporte, agregar paquetes y actualizar sus valores. Tambien, una vez finalizado el viaje, se eliminan los paquetes 
[source, java]
----
  private String matricula;
  private double capacidad; // peso
  private double cargaMax; // volumen
  private double cargaActual; //inicialmente es 0, carga Actual<=cargaMax
  private boolean tieneRefrigeracion;
  private double costoKm;
  private HashSet<Paquete> paquetes;
  private boolean estaEnViaje;
  private String destino;
  public Transporte(String matricula, double cargaMax, double capacidad, double costoKm, boolean tieneRefrigeracion)
  public void cargarPaquete(Paquete p) {
    if (cargaActual <= cargaMax) {
      paquetes.add(p);
      cargaActual = cargaActual + p.getVolumen();
    }
  }
  public void eliminarPaquete() {
    paquetes.removeAll(paquetes);
  }
----

Tambien tenemos todas las clases que hereddan de transporte

[source, java]
----
  public class Trailer extends Transporte
    private double seguro;
    public Trailer(String matricula, double cargaMax, double capacidad, boolean tieneRefrigeracion, double costoKm,double segCarga)
  @Override suma al costo total del viaje los extras que son exclusivos de los trailer
  public double costoViaje() {
    return seguro;
  }

  public class MegaTrailer extends Transporte
  private double costoComida;
  private double costoFijo;
  private double seguro;
  public MegaTrailer(String matricula, double cargaMax, double capacidad, boolean tieneRefrigeracion, double costoKm, double segCarga, double costoFijo, double costoComida)
  @Override suma al costo total del viaje los extras que son exclusivos de los mega trailer
  public double costoViaje() {
    return costoComida + costoFijo + seguro;
  }

  public class Flete extends Transporte
  private int acompañante;
  private int costo acompañante;
  public Flete(String matricula, double cargaMax, double capacidad, double costoKm, int cantAcompaniantes, double costoPorAcompaniante)
  @Override
  public double costoViaje() {
    return cantAcompaniantes * costoPorAcompaniante;
  }
----

=== Paquete y destino
[source, java]
----
  public class Paquete{
  private int peso;
  private int volumen;
  private String destino;
  private boolean refrigeracion;
  public Paquete (String destino, double peso, double volumen, boolean refrigeracion)
  }
  public class Destino{
  private String destino;
  private int km;
  public Destino(String destino, int km)
  }
----
